
server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

#日志记录级别


#热启动,不重启显示更新部分
#spring:
#  thymeleaf:
#    cache: false

#映射文件，必须放在resources下
mybatis:
#  映射文件路径
#  mapper-locations: classpath*:com.example.jfrd.modular.*.dao.mapper/*.xml
  mapper-locations: classpath*:mapper/*.xml
#  实体类别名包路径
  type-aliases-package: com.example.jfrd.modular.*.pojo
#  global-config:
#    db-column-underline: true   # 驼峰下划线转换
#    capital-mode: false   #数据库大写下划线转换
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置返回数据（column下划线命名&&返回Java实体是驼峰命名），自动匹配无需as（没开启这个，SQL需要写as； selece user_id as userId）
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com.jfrd: debug
    spring: info
